"""Shared helpers for the p7 fast-mesh->BRep prototype.

Mesh generation, welding, volume/validity probes, timing. Kept separate from
m2b.py (the conversion logic under test) so benchmarks can mix and match.
"""
from __future__ import annotations

import time

import numpy as np

from OCP.BRepGProp import BRepGProp
from OCP.GProp import GProp_GProps
from OCP.BRepCheck import BRepCheck_Analyzer
from OCP.TopAbs import TopAbs_ShapeEnum
from OCP.TopExp import TopExp_Explorer, TopExp
from OCP.TopTools import TopTools_IndexedMapOfShape


def _wrapped(shape):
    return getattr(shape, "wrapped", shape)


def volume(shape) -> float:
    props = GProp_GProps()
    BRepGProp.VolumeProperties_s(_wrapped(shape), props)
    return props.Mass()


def area(shape) -> float:
    props = GProp_GProps()
    BRepGProp.SurfaceProperties_s(_wrapped(shape), props)
    return props.Mass()


def is_valid(shape) -> bool:
    return BRepCheck_Analyzer(_wrapped(shape)).IsValid()


_ENUM = {"face": TopAbs_ShapeEnum.TopAbs_FACE,
         "shell": TopAbs_ShapeEnum.TopAbs_SHELL,
         "edge": TopAbs_ShapeEnum.TopAbs_EDGE,
         "vertex": TopAbs_ShapeEnum.TopAbs_VERTEX,
         "solid": TopAbs_ShapeEnum.TopAbs_SOLID}


def count(shape, kind):
    """Count *occurrences* of a sub-shape (a shared edge counts once per face)."""
    exp = TopExp_Explorer(_wrapped(shape), _ENUM[kind])
    n = 0
    while exp.More():
        n += 1
        exp.Next()
    return n


def count_distinct(shape, kind):
    """Count DISTINCT sub-shapes by TShape identity (true topology size)."""
    m = TopTools_IndexedMapOfShape()
    TopExp.MapShapes_s(_wrapped(shape), _ENUM[kind], m)
    return m.Extent()


def weld(verts, tris, decimals=6):
    """Merge coincident vertices -> (welded_verts float64, remapped_tris int64).

    Mirrors build123d's own dedup (Mesher rounds to TOLERANCE 1e-6 -> 6 digits).
    """
    key = np.round(np.asarray(verts, dtype=np.float64), decimals)
    uniq, inv = np.unique(key, axis=0, return_inverse=True)
    inv = inv.reshape(-1)
    new_tris = inv[np.asarray(tris)].astype(np.int64)
    return uniq.astype(np.float64), new_tris


def to_manifold(verts, tris, do_weld=True):
    import manifold3d as m
    if do_weld:
        verts, tris = weld(verts, tris)
    mesh = m.Mesh(vert_properties=np.ascontiguousarray(verts, dtype=np.float32),
                  tri_verts=np.ascontiguousarray(tris, dtype=np.uint32))
    return m.Manifold(mesh)


def manifold_to_arrays(man):
    """Manifold -> (verts Nx3 float64, tris Mx3 int64). Already welded."""
    mesh = man.to_mesh()
    verts = np.asarray(mesh.vert_properties)[:, :3].astype(np.float64)
    tris = np.asarray(mesh.tri_verts).astype(np.int64)
    return verts, tris


def timed(fn, *a, **k):
    t0 = time.perf_counter()
    r = fn(*a, **k)
    return r, time.perf_counter() - t0


# --------------------------------------------------------------------------
# Test-mesh generation
# --------------------------------------------------------------------------

def sphere_mesh(triangle_target):
    """A welded sphere mesh of roughly `triangle_target` triangles.

    manifold3d's sphere is generated by circular_segments; an icosphere-style
    refine(n) then multiplies triangle count by n^2 while staying a guaranteed
    valid 2-manifold. We pick segments + refine to hit the target, then return
    (verts float64, tris int64). r = 20.
    """
    import manifold3d as m
    # base sphere ~ a few hundred tris
    base = m.Manifold.sphere(20, circular_segments=32)
    base_tris = base.num_tri()
    if triangle_target <= base_tris:
        # coarsen via fewer segments
        for segs in (8, 12, 16, 24, 32):
            cand = m.Manifold.sphere(20, circular_segments=segs)
            if cand.num_tri() >= triangle_target:
                man = cand
                break
        else:
            man = base
    else:
        refine = max(1, int(round((triangle_target / base_tris) ** 0.5)))
        man = base.refine(refine) if refine > 1 else base
    return manifold_to_arrays(man)


def sphere_mesh_manifold(triangle_target):
    """Same as sphere_mesh but also returns the source Manifold (for volume ref)."""
    import manifold3d as m
    base = m.Manifold.sphere(20, circular_segments=32)
    base_tris = base.num_tri()
    if triangle_target <= base_tris:
        for segs in (8, 12, 16, 24, 32):
            cand = m.Manifold.sphere(20, circular_segments=segs)
            if cand.num_tri() >= triangle_target:
                man = cand
                break
        else:
            man = base
    else:
        refine = max(1, int(round((triangle_target / base_tris) ** 0.5)))
        man = base.refine(refine) if refine > 1 else base
    v, t = manifold_to_arrays(man)
    return v, t, man
