# Auto-generated by scad2b3d.py (OpenSCAD -> build123d prototype)
# Source: CSG-modules.scad
from build123d import *
from build123d import Align
import math

# ---- OpenSCAD compatibility shims ----
# OpenSCAD trig is in DEGREES.
def _sin(a): return math.sin(math.radians(a))
def _cos(a): return math.cos(math.radians(a))
def _tan(a): return math.tan(math.radians(a))

# ---- generated runtime helpers (OpenSCAD value/geometry semantics) ----

def _raise(msg):
    raise NotImplementedError(msg)

def _group(parts):
    """OpenSCAD implicit aggregation (top level, `for`, module bodies, union of
    disjoint parts) -> a build123d Compound.

    OpenSCAD's CSG tree only fuses geometry into one mesh at F6 *render* time;
    the script-level tree is a *group*. Folding N parts with pairwise OCCT
    booleans (`a + b + c + ...`) is the O(n^2) build123d performance cliff and
    is also unnecessary for the disjoint case. A Compound is O(n), exports
    correctly to STL, and is the faithful representation of the CSG group node.
    Explicit `union()` of overlapping solids still uses real `+` booleans.
    """
    parts = [p for p in parts if p is not None]
    if not parts:
        return None
    if len(parts) == 1:
        return parts[0]
    return Compound(children=parts)

def _v3(v):
    v = list(v)
    while len(v) < 3:
        v.append(0)
    return v[:3]

def _orange(start, end, step):
    """OpenSCAD range [start:step:end] - inclusive of end."""
    out, x = [], start
    if step == 0:
        return out
    if step > 0:
        while x <= end + 1e-9:
            out.append(x)
            x += step
    else:
        while x >= end - 1e-9:
            out.append(x)
            x += step
    return out

def _norm(v):
    return math.sqrt(sum(c * c for c in v))

def _cross(a, b):
    return [a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0]]

def _atan2(y, x):
    return math.degrees(math.atan2(y, x))

def _atan(x):
    return math.degrees(math.atan(x))

def _asin(x):
    return math.degrees(math.asin(x))

def _acos(x):
    return math.degrees(math.acos(x))

def _ostr(*args):
    return "".join(str(a) for a in args)

def _concat(*args):
    out = []
    for a in args:
        if isinstance(a, (list, tuple)):
            out.extend(a)
        else:
            out.append(a)
    return out

def _colored(shape, color):
    if shape is not None:
        shape.color = color
    return shape

def _location_from_matrix(m):
    """Best-effort: rigid (rotation+translation) part of a 4x4 multmatrix."""
    import numpy as np
    a = np.array(m, dtype=float)
    if a.shape == (3, 4):
        a = np.vstack([a, [0, 0, 0, 1]])
    loc = Location()
    loc.wrapped  # touch
    from build123d import Matrix
    return Location(Matrix(a.tolist()))

def _polyhedron(points, faces):
    """OpenSCAD polyhedron -> Solid(Shell(faces)). Fragile for non-planar."""
    occ_faces = []
    for f in faces:
        pts = [points[i] for i in f]
        wire = Wire.make_polygon([tuple(p) for p in pts], close=True)
        occ_faces.append(Face(wire))
    shell = Shell(occ_faces)
    try:
        return Solid(shell)
    except Exception:
        return shell

def _polygon_paths(points, paths):
    """OpenSCAD polygon with explicit paths -> outer face minus holes."""
    faces = []
    for path in paths:
        pts = [tuple(points[i]) for i in path]
        faces.append(Polygon(*pts))
    if not faces:
        return None
    result = faces[0]
    for hole in faces[1:]:
        result = result - hole
    return result

def _is_undef(x):
    return x is None

def _is_list(x):
    return isinstance(x, (list, tuple))

def _is_num(x):
    return isinstance(x, (int, float)) and not isinstance(x, bool)

def _is_string(x):
    return isinstance(x, str)

def _is_bool(x):
    return isinstance(x, bool)

def _lookup(key, table):
    table = sorted(table, key=lambda kv: kv[0])
    if key <= table[0][0]:
        return table[0][1]
    if key >= table[-1][0]:
        return table[-1][1]
    for i in range(len(table) - 1):
        x0, y0 = table[i]
        x1, y1 = table[i + 1]
        if x0 <= key <= x1:
            t = (key - x0) / (x1 - x0)
            return y0 + t * (y1 - y0)
    return table[-1][1]


def body():
    _parts = []
    _parts.append(_colored(Sphere(10), Color('Blue')))
    return _group(_parts)

def intersector():
    _parts = []
    _parts.append(_colored(Box(15, 15, 15), Color('Red')))
    return _group(_parts)

def holeObject():
    _parts = []
    _parts.append(_colored(Cylinder(5, 20), Color('Lime')))
    return _group(_parts)

def intersected():
    _parts = []
    _parts.append(((body()) & (intersector())))
    return _group(_parts)

def holeA():
    _parts = []
    _parts.append((Rot(0, 90, 0) * holeObject()))
    return _group(_parts)

def holeB():
    _parts = []
    _parts.append((Rot(90, 0, 0) * holeObject()))
    return _group(_parts)

def holeC():
    _parts = []
    _parts.append(holeObject())
    return _group(_parts)

def holes():
    _parts = []
    _parts.append(((holeA()) + (holeB()) + (holeC())))
    return _group(_parts)

def helpers():
    _parts = []
    _parts.append(scale(((Pos(-30, 0, -40) * (intersected() + (Pos(-15, 0, -35) * body()) + (Pos(15, 0, -35) * intersector()) + (Pos(-7.5, 0, -17.5) * (Rot(0, 30, 0) * line())) + (Pos(7.5, 0, -17.5) * (Rot(0, -30, 0) * line())))) + (Pos(30, 0, -40) * (holes() + (Pos(-10, 0, -35) * holeA()) + (Pos(10, 0, -35) * holeB()) + (Pos(30, 0, -35) * holeC()) + (Pos(5, 0, -17.5) * (Rot(0, -20, 0) * line())) + (Pos(-5, 0, -17.5) * (Rot(0, 30, 0) * line())) + (Pos(15, 0, -17.5) * (Rot(0, -45, 0) * line())))) + (Pos(-20, 0, -22.5) * (Rot(0, 45, 0) * line())) + (Pos(20, 0, -22.5) * (Rot(0, -45, 0) * line()))), by=0.5))
    return _group(_parts)

def line():
    _parts = []
    _parts.append(_colored(Cylinder(1, 10), Color('Black')))
    return _group(_parts)

# ---- top-level geometry ----
_parts = []

debug = True
_dollar_fs = 0.1
_dollar_fa = 5
_parts.append(((((body()) & (intersector()))) - (holes())))
if debug:
    _parts.append(helpers())
print('ECHO:', 'version=', [2024, 1, 0], 'bar=', 'foo', 'baz=', [1, '2'])

# Combine all top-level geometry. OpenSCAD's top level is an
# IMPLICIT GROUP (a CSG group node, not a boolean union): disjoint
# parts are merged into one mesh only at F6 render. We mirror that
# with a Compound -- O(n) and faithful -- instead of folding N
# pairwise OCCT booleans (the O(n^2) build123d CSG cliff).
result = _group(_parts)

if __name__ == '__main__':
    if result is not None:
        print('result:', result)
        try:
            export_stl(result, 'out.stl')
            print('exported out.stl')
        except Exception as _e:
            print('export skipped:', _e)
